### ISSUE TITLE
Lost index removing repo in the Repo list

### ISSUE THREAD

**Issue by luipir** [boundlessgeo/qgis-geogig-plugin#11]
removing a repo from the list of repo, but a repo that is in the middle of the list (not the last one, leave the repo list view in a wrong state generating exceptions. The only way to reset repo list is to manually remove repo from the geogit repo path.

this seems and error on managing a data list pointing to a obsolete item index

**Comment by alexbruy** [comment]
Seems already fixed in master. Reopen if necessary
