### ISSUE TITLE
No tracking after editing

### ISSUE THREAD

**Issue by TimJMartin** [boundlessgeo/qgis-geogig-plugin#30]
I am following the guide to test Geogig.

I create a new repo, add a shapefile layer to that repo.

Edit the layer (remove a polygon) and then save edits and toggle editing to off. 

It says I should receive a dialog box asking for comments about the edits and when saved i should see the changes in the repo history.

I do not get this dialog box and there does not seem to be any history apart from staging the original data

What am i missing?

**Comment by alexbruy** [comment]
Docs are a bit outdated. In latest plugin you should commit your edits manually by selecting `GeoGig → Update repository with this version` from layer context menu.
