### ISSUE TITLE
Allow directory browsing when configuring base folder for repositories

### ISSUE THREAD

**Issue by drownedfrog** [boundlessgeo/qgis-geogig-plugin#4]
Currently no browse button to navigate file system when configuring the `Base folder for repositories` path. This makes adding a new directory cumbersome.

Please add a directory dialogue button after the path for user to click on.

**Comment by luipir** [comment]
in this moment there is a unique folder <home>/geogig where all repo are located

what do you need? 
1) decide the base location of the folder where locate all repos? => kind of plugin setting
2) decide location for each repo? => during repo creation
