### ISSUE TITLE
Provide a docked GeoGig navigator dialogue

### ISSUE THREAD

**Issue by drownedfrog** [boundlessgeo/qgis-geogig-plugin#5]
Current dialogue is non-dockable.

I would prefer the dialogue to dock with the Layers Panel, much like qNote does or perhaps the attribute table.

**Comment by luipir** [comment]
I strongly agree

**Comment by luipir** [comment]
well I should notice that the general interface can be docked, but probably it is better to use the interface usign layer contextual menu. In this way no need of docked od dialog interfaces .

**Comment by alexbruy** [comment]
Already fixed
